global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'titan-core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['titan-core:8080']
